object AuswahlForm: TAuswahlForm
  Left = 401
  Top = 118
  Anchors = [akTop, akRight]
  BorderStyle = bsNone
  ClientHeight = 422
  ClientWidth = 411
  Color = clBtnFace
  Constraints.MinHeight = 200
  Constraints.MinWidth = 300
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  KeyPreview = True
  OnClose = FormClose
  OnKeyDown = FormKeyDown
  OnMouseDown = FormMouseDown
  OnMouseMove = FormMouseMove
  OnMouseUp = FormMouseUp
  OnResize = FormResize
  OnShow = FormShow
  TextHeight = 13
  object ContainerPanelAuswahlform: TNempPanel
    Tag = 2
    Left = 0
    Top = 0
    Width = 411
    Height = 422
    Align = alClient
    BevelOuter = bvNone
    ParentShowHint = False
    ShowHint = True
    TabOrder = 0
    OnMouseDown = ContainerPanelAuswahlformMouseDown
    OnMouseMove = ContainerPanelAuswahlformMouseMove
    OnMouseUp = ContainerPanelAuswahlformMouseUp
    Ratio = 0
    DrawMode = dm_Windows
    DrawFrame = False
    BackgroundBasePanel = True
    OnPaintBackground = ContainerPanelAuswahlformPaintBackground
    OwnerDraw = False
    object pnlSplit: TPanel
      AlignWithMargins = True
      Left = 8
      Top = 6
      Width = 395
      Height = 408
      Margins.Left = 8
      Margins.Top = 6
      Margins.Right = 8
      Margins.Bottom = 8
      Align = alClient
      BevelOuter = bvNone
      TabOrder = 0
      ExplicitLeft = 7
      ExplicitTop = 2
      ExplicitWidth = 397
      ExplicitHeight = 413
    end
  end
end
