object ExtendedControlForm: TExtendedControlForm
  Left = 0
  Top = 0
  Anchors = [akTop, akRight]
  BorderStyle = bsNone
  Caption = 'ExtendedControlForm'
  ClientHeight = 200
  ClientWidth = 400
  Color = clBtnFace
  Constraints.MinHeight = 200
  Constraints.MinWidth = 300
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  KeyPreview = True
  OnClose = FormClose
  OnKeyDown = FormKeyDown
  OnMouseDown = FormMouseDown
  OnMouseMove = FormMouseMove
  OnMouseUp = FormMouseUp
  OnResize = FormResize
  OnShow = FormShow
  TextHeight = 13
  object ContainerPanelExtendedControlsForm: TNempPanel
    Tag = 4
    Left = 0
    Top = 0
    Width = 400
    Height = 200
    Align = alClient
    BevelOuter = bvNone
    TabOrder = 0
    OnMouseDown = ContainerPanelExtendedControlsFormMouseDown
    OnMouseMove = ContainerPanelExtendedControlsFormMouseMove
    OnMouseUp = ContainerPanelExtendedControlsFormMouseUp
    Ratio = 0
    DrawMode = dm_Windows
    DrawFrame = False
    BackgroundBasePanel = True
    OnPaintBackground = ContainerPanelExtendedControlsFormPaintBackground
    OwnerDraw = False
    object pnlSplit: TPanel
      AlignWithMargins = True
      Left = 8
      Top = 6
      Width = 384
      Height = 186
      Margins.Left = 8
      Margins.Top = 6
      Margins.Right = 8
      Margins.Bottom = 8
      Align = alClient
      BevelOuter = bvNone
      TabOrder = 0
      ExplicitLeft = 7
      ExplicitTop = 2
      ExplicitWidth = 386
      ExplicitHeight = 191
    end
  end
end
