object FormHeadsetControl: TFormHeadsetControl
  Left = 0
  Top = 0
  Caption = 'Nemp: Headset control'
  ClientHeight = 149
  ClientWidth = 418
  Color = clBtnFace
  Constraints.MaxHeight = 188
  Constraints.MinHeight = 188
  Constraints.MinWidth = 400
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -12
  Font.Name = 'Segoe UI'
  Font.Style = []
  Position = poMainFormCenter
  OnAfterMonitorDpiChanged = FormAfterMonitorDpiChanged
  OnClose = FormClose
  OnCreate = FormCreate
  OnShow = FormShow
  TextHeight = 15
  object pnlBars: TPanel
    Left = 0
    Top = 117
    Width = 418
    Height = 32
    Align = alBottom
    TabOrder = 0
    ExplicitWidth = 434
    object HeadsetTimeLbl: TLabel
      AlignWithMargins = True
      Left = 9
      Top = 9
      Width = 34
      Height = 16
      Margins.Left = 8
      Margins.Top = 8
      Margins.Right = 0
      Margins.Bottom = 6
      Align = alLeft
      Alignment = taRightJustify
      AutoSize = False
      Caption = '00:00'
      ExplicitLeft = 0
      ExplicitTop = 0
      ExplicitHeight = 48
    end
    object rbHeadsetTrack: TProgressRangeBar
      AlignWithMargins = True
      Left = 43
      Top = 7
      Width = 265
      Height = 18
      Margins.Left = 0
      Margins.Top = 6
      Margins.Right = 0
      Margins.Bottom = 6
      OnScroll = rbHeadsetTrackScroll
      OnStep = rbHeadsetTrackStep
      OnEndScroll = rbHeadsetTrackEndScroll
      RangeMin = 0
      RangeMax = 100
      RangeMaxNorm = 1.000000000000000000
      Orientation = trHorizontal
      ButtonMode = bmCentered
      Style = nsbStyleWindows
      TrackBarMargin = 8
      Position = 0
      DefaultPosition = 0
      AllowRange = True
      RangeActive = False
      TrackButton.Colors.FrameColor = clActiveBorder
      TrackButton.Colors.FrameHighlightColor = clActiveBorder
      TrackButton.Colors.FrameDisabledColor = clInactiveBorder
      TrackButton.Colors.BrushColor = clBtnFace
      TrackButton.Colors.BrushHighlightColor = clBtnHighlight
      TrackButton.Colors.BrushDisabledColor = clBtnShadow
      TrackButton.Colors.FocusRectColor = clHighlight
      TrackButton.FrameWidth = 1
      TrackButton.Radius = 4
      TrackButton.VisibleMode = vAlways
      TrackButton.Thickness = 12
      TrackButton.Length = 20
      RangeButtonMin.Colors.FrameColor = clActiveBorder
      RangeButtonMin.Colors.FrameHighlightColor = clActiveBorder
      RangeButtonMin.Colors.FrameDisabledColor = clInactiveBorder
      RangeButtonMin.Colors.BrushColor = clBtnFace
      RangeButtonMin.Colors.BrushHighlightColor = clBtnHighlight
      RangeButtonMin.Colors.BrushDisabledColor = clBtnShadow
      RangeButtonMin.Colors.FocusRectColor = clHighlight
      RangeButtonMin.FrameWidth = 1
      RangeButtonMin.Radius = 4
      RangeButtonMin.VisibleMode = vAlways
      RangeButtonMin.Thickness = 12
      RangeButtonMin.Length = 18
      RangeButtonMax.Colors.FrameColor = clActiveBorder
      RangeButtonMax.Colors.FrameHighlightColor = clActiveBorder
      RangeButtonMax.Colors.FrameDisabledColor = clInactiveBorder
      RangeButtonMax.Colors.BrushColor = clBtnFace
      RangeButtonMax.Colors.BrushHighlightColor = clBtnHighlight
      RangeButtonMax.Colors.BrushDisabledColor = clBtnShadow
      RangeButtonMax.Colors.FocusRectColor = clHighlight
      RangeButtonMax.FrameWidth = 1
      RangeButtonMax.Radius = 4
      RangeButtonMax.VisibleMode = vAlways
      RangeButtonMax.Thickness = 12
      RangeButtonMax.Length = 18
      TrackBar.Colors.FrameColor = clActiveBorder
      TrackBar.Colors.FrameHighlightColor = clActiveBorder
      TrackBar.Colors.FrameDisabledColor = clInactiveBorder
      TrackBar.Colors.BrushColor = clBtnFace
      TrackBar.Colors.BrushHighlightColor = clBtnHighlight
      TrackBar.Colors.BrushDisabledColor = clBtnShadow
      TrackBar.Colors.FocusRectColor = clHighlight
      TrackBar.FrameWidth = 1
      TrackBar.Radius = 4
      TrackBar.VisibleMode = vAlways
      TrackBar.Thickness = 8
      ProgressBar.Colors.FrameColor = clActiveBorder
      ProgressBar.Colors.FrameHighlightColor = clActiveBorder
      ProgressBar.Colors.FrameDisabledColor = clInactiveBorder
      ProgressBar.Colors.BrushColor = clHighlight
      ProgressBar.Colors.BrushHighlightColor = clBtnHighlight
      ProgressBar.Colors.BrushDisabledColor = clBtnShadow
      ProgressBar.Colors.FocusRectColor = clHighlight
      ProgressBar.FrameWidth = 1
      ProgressBar.Radius = 4
      ProgressBar.VisibleMode = vAlways
      ProgressBar.Thickness = 8
      RangeBar.Colors.FrameColor = clActiveBorder
      RangeBar.Colors.FrameHighlightColor = clActiveBorder
      RangeBar.Colors.FrameDisabledColor = clInactiveBorder
      RangeBar.Colors.BrushColor = clBtnFace
      RangeBar.Colors.BrushHighlightColor = clBtnHighlight
      RangeBar.Colors.BrushDisabledColor = clBtnShadow
      RangeBar.Colors.FocusRectColor = clHighlight
      RangeBar.FrameWidth = 1
      RangeBar.Radius = 4
      RangeBar.VisibleMode = vAlways
      RangeBar.Thickness = 4
      Align = alClient
      ExplicitWidth = 261
    end
    object BtnMute: TSkinButton
      AlignWithMargins = True
      Left = 312
      Top = 4
      Width = 24
      Height = 24
      Margins.Left = 4
      Margins.Right = 0
      Align = alRight
      DrawMode = dm_Windows
      TabOrder = 1
      Caption = 'SkinButton1'
      ExplicitLeft = 308
    end
    object rbVolume: TProgressRangeBar
      AlignWithMargins = True
      Left = 336
      Top = 7
      Width = 89
      Height = 18
      Margins.Left = 0
      Margins.Top = 6
      Margins.Right = 12
      Margins.Bottom = 6
      OnScroll = rbVolumeScroll
      RangeMin = 0
      RangeMax = 100
      RangeMaxNorm = 1.000000000000000000
      Orientation = trHorizontal
      ButtonMode = bmNested
      Style = nsbStyleWindows
      TrackBarMargin = 4
      Position = 0
      DefaultPosition = 0
      AllowRange = False
      RangeActive = False
      TrackButton.Colors.FrameColor = clActiveBorder
      TrackButton.Colors.FrameHighlightColor = clActiveBorder
      TrackButton.Colors.FrameDisabledColor = clInactiveBorder
      TrackButton.Colors.BrushColor = clBtnFace
      TrackButton.Colors.BrushHighlightColor = clBtnHighlight
      TrackButton.Colors.BrushDisabledColor = clBtnShadow
      TrackButton.Colors.FocusRectColor = clHighlight
      TrackButton.FrameWidth = 1
      TrackButton.Radius = 4
      TrackButton.VisibleMode = vAlways
      TrackButton.Thickness = 12
      TrackButton.Length = 20
      RangeButtonMin.Colors.FrameColor = clActiveBorder
      RangeButtonMin.Colors.FrameHighlightColor = clActiveBorder
      RangeButtonMin.Colors.FrameDisabledColor = clInactiveBorder
      RangeButtonMin.Colors.BrushColor = clBtnFace
      RangeButtonMin.Colors.BrushHighlightColor = clBtnHighlight
      RangeButtonMin.Colors.BrushDisabledColor = clBtnShadow
      RangeButtonMin.Colors.FocusRectColor = clHighlight
      RangeButtonMin.FrameWidth = 1
      RangeButtonMin.Radius = 4
      RangeButtonMin.VisibleMode = vAlways
      RangeButtonMin.Thickness = 12
      RangeButtonMin.Length = 18
      RangeButtonMax.Colors.FrameColor = clActiveBorder
      RangeButtonMax.Colors.FrameHighlightColor = clActiveBorder
      RangeButtonMax.Colors.FrameDisabledColor = clInactiveBorder
      RangeButtonMax.Colors.BrushColor = clBtnFace
      RangeButtonMax.Colors.BrushHighlightColor = clBtnHighlight
      RangeButtonMax.Colors.BrushDisabledColor = clBtnShadow
      RangeButtonMax.Colors.FocusRectColor = clHighlight
      RangeButtonMax.FrameWidth = 1
      RangeButtonMax.Radius = 4
      RangeButtonMax.VisibleMode = vAlways
      RangeButtonMax.Thickness = 12
      RangeButtonMax.Length = 18
      TrackBar.Colors.FrameColor = clActiveBorder
      TrackBar.Colors.FrameHighlightColor = clActiveBorder
      TrackBar.Colors.FrameDisabledColor = clInactiveBorder
      TrackBar.Colors.BrushColor = clBtnFace
      TrackBar.Colors.BrushHighlightColor = clBtnHighlight
      TrackBar.Colors.BrushDisabledColor = clBtnShadow
      TrackBar.Colors.FocusRectColor = clHighlight
      TrackBar.FrameWidth = 1
      TrackBar.Radius = 4
      TrackBar.VisibleMode = vAlways
      TrackBar.Thickness = 8
      ProgressBar.Colors.FrameColor = clActiveBorder
      ProgressBar.Colors.FrameHighlightColor = clActiveBorder
      ProgressBar.Colors.FrameDisabledColor = clInactiveBorder
      ProgressBar.Colors.BrushColor = clHighlight
      ProgressBar.Colors.BrushHighlightColor = clBtnHighlight
      ProgressBar.Colors.BrushDisabledColor = clBtnShadow
      ProgressBar.Colors.FocusRectColor = clHighlight
      ProgressBar.FrameWidth = 1
      ProgressBar.Radius = 4
      ProgressBar.VisibleMode = vAlways
      ProgressBar.Thickness = 8
      RangeBar.Colors.FrameColor = clActiveBorder
      RangeBar.Colors.FrameHighlightColor = clActiveBorder
      RangeBar.Colors.FrameDisabledColor = clInactiveBorder
      RangeBar.Colors.BrushColor = clBtnFace
      RangeBar.Colors.BrushHighlightColor = clBtnHighlight
      RangeBar.Colors.BrushDisabledColor = clBtnShadow
      RangeBar.Colors.FocusRectColor = clHighlight
      RangeBar.FrameWidth = 1
      RangeBar.Radius = 4
      RangeBar.VisibleMode = vAlways
      RangeBar.Thickness = 4
      Align = alRight
      ExplicitLeft = 332
    end
  end
  object pnlContainer: TPanel
    AlignWithMargins = True
    Left = 0
    Top = 0
    Width = 418
    Height = 117
    Margins.Left = 0
    Margins.Top = 0
    Margins.Right = 0
    Margins.Bottom = 0
    Align = alClient
    TabOrder = 1
    ExplicitWidth = 434
    object imgCover: TImage
      AlignWithMargins = True
      Left = 9
      Top = 9
      Width = 100
      Height = 100
      Margins.Left = 8
      Margins.Top = 8
      Margins.Right = 8
      Margins.Bottom = 8
      Align = alLeft
      Proportional = True
      Stretch = True
      OnMouseDown = imgCoverMouseDown
      OnMouseMove = imgCoverMouseMove
    end
    object pnlInfo: TPanel
      Left = 117
      Top = 1
      Width = 320
      Height = 116
      Align = alClient
      BevelOuter = bvNone
      TabOrder = 0
      OnMouseDown = pnlInfoMouseDown
      ExplicitWidth = 316
      ExplicitHeight = 115
      object PlayerTitleLabel: TLabel
        Left = 8
        Top = 28
        Width = 9
        Height = 13
        Caption = '...'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Tahoma'
        Font.Style = [fsBold]
        ParentFont = False
        ShowAccelChar = False
      end
      object PlayerArtistLabel: TLabel
        Left = 8
        Top = 8
        Width = 9
        Height = 15
        Caption = '...'
        ShowAccelChar = False
      end
      object BtnHeadsetPlaynow: TSkinButton
        Left = 99
        Top = 75
        Width = 32
        Height = 32
        Hint = 'Add file to playlist and begin playback from current position'
        DrawMode = dm_Windows
        TabOrder = 0
        OnClick = BtnHeadsetPlaynowClick
      end
      object BtnHeadsetToPlaylist: TSkinButton
        Left = 137
        Top = 75
        Width = 32
        Height = 32
        Hint = 'Add current file to playlist (Right click for options)'
        DrawMode = dm_Windows
        PopupMenu = PopupHeadset
        TabOrder = 1
        OnClick = BtnHeadsetToPlaylistClick
      end
      object BtnLoadHeadset: TSkinButton
        Left = 193
        Top = 75
        Width = 32
        Height = 32
        Hint = 'Load selected file into headset (Ctrl+H)'
        DrawMode = dm_Windows
        TabOrder = 2
        Visible = False
      end
      object PlayPauseHeadSetBtn: TSkinButton
        Left = 8
        Top = 75
        Width = 32
        Height = 32
        DrawMode = dm_Windows
        TabOrder = 3
        OnClick = PlayPauseHeadSetBtnClick
      end
      object StopHeadSetBtn: TSkinButton
        Left = 46
        Top = 75
        Width = 32
        Height = 32
        DrawMode = dm_Windows
        Images = vilIcons
        TabOrder = 4
        OnClick = StopHeadSetBtnClick
      end
      object BtnHeadsetRating: TRatingButton
        Left = 8
        Top = 51
        Width = 80
        Height = 16
        DrawMode = dm_Windows
        Images = vilIcons
        TabOrder = 5
        TransparentBackground = True
        Visible = False
        StyleElements = [seFont, seBorder]
        Rating = 120
        AllowChangeRating = True
        OnRatingChanged = BtnHeadsetRatingRatingChanged
        StarFullImageIndex = 0
        StarHalfImageIndex = 1
        StarEmptyImageIndex = 2
      end
      object Button1: TButton
        Left = 248
        Top = 40
        Width = 75
        Height = 25
        Caption = 'Button1'
        TabOrder = 6
        OnClick = Button1Click
      end
      object Button2: TButton
        Left = 240
        Top = 71
        Width = 75
        Height = 25
        Caption = 'Button2'
        TabOrder = 7
        OnClick = Button2Click
      end
    end
  end
  object HeadsetTimer: TTimer
    OnTimer = HeadsetTimerTimer
    Left = 32
    Top = 32
  end
  object vilIcons: TVirtualImageList
    AutoFill = True
    Images = <
      item
        CollectionIndex = 0
        CollectionName = 'StarFull'
        Name = 'StarFull'
      end
      item
        CollectionIndex = 1
        CollectionName = 'StarHalf'
        Name = 'StarHalf'
      end
      item
        CollectionIndex = 2
        CollectionName = 'StarEmpty'
        Name = 'StarEmpty'
      end
      item
        CollectionIndex = 3
        CollectionName = 'PlayCount'
        Name = 'PlayCount'
      end>
    ImageCollection = DataModuleGui.ICIcons
    Left = 217
    Top = 17
  end
  object PopupHeadset: TPopupMenu
    Left = 315
    Top = 18
    object PM_H_EnqueueEndOfPlaylist: TMenuItem
      Caption = 'Enqueue (at the end of the playlist)'
      OnClick = InsertHeadsetToPlaylistClick
    end
    object PM_H_PlayAndClearPlaylist: TMenuItem
      Tag = 1
      Caption = 'Play (and clear current playlist)'
      OnClick = InsertHeadsetToPlaylistClick
    end
    object PM_H_EnqueueAfterCurrentTitle: TMenuItem
      Tag = 2
      Caption = 'Enqueue (after the current title)'
      OnClick = InsertHeadsetToPlaylistClick
    end
    object PM_H_JustPlay: TMenuItem
      Tag = 3
      Caption = 'Just play the track (don'#39't change the playlist)'
      OnClick = InsertHeadsetToPlaylistClick
    end
  end
end
