object MedienlisteForm: TMedienlisteForm
  Left = 689
  Top = 113
  BorderStyle = bsNone
  ClientHeight = 250
  ClientWidth = 574
  Color = clBtnFace
  Constraints.MinHeight = 200
  Constraints.MinWidth = 300
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  KeyPreview = True
  OnClose = FormClose
  OnKeyDown = FormKeyDown
  OnMouseDown = FormMouseDown
  OnMouseMove = FormMouseMove
  OnMouseUp = FormMouseUp
  OnResize = FormResize
  OnShow = FormShow
  TextHeight = 13
  object ContainerPanelMedienBibForm: TNempPanel
    Tag = 3
    Left = 0
    Top = 0
    Width = 574
    Height = 250
    Align = alClient
    BevelOuter = bvNone
    DoubleBuffered = False
    ParentDoubleBuffered = False
    TabOrder = 0
    OnMouseDown = ContainerPanelMedienBibFormMouseDown
    OnMouseMove = ContainerPanelMedienBibFormMouseMove
    OnMouseUp = ContainerPanelMedienBibFormMouseUp
    Ratio = 0
    DrawMode = dm_Windows
    DrawFrame = False
    BackgroundBasePanel = True
    OnPaintBackground = ContainerPanelMedienBibFormPaintBackground
    OwnerDraw = False
    object pnlSplit: TPanel
      AlignWithMargins = True
      Left = 8
      Top = 6
      Width = 558
      Height = 236
      Margins.Left = 8
      Margins.Top = 6
      Margins.Right = 8
      Margins.Bottom = 8
      Align = alClient
      BevelOuter = bvNone
      TabOrder = 0
      ExplicitLeft = 7
      ExplicitTop = 2
      ExplicitWidth = 560
      ExplicitHeight = 241
    end
  end
end
