// Project: Nemp - Noch ein MP3-Player
// Generated by HelpNDoc - https://www.helpndoc.com

unit NempHelp;

interface

const
  // Format: HELP_help-id = help-context
  HELP_Nemp_Main = 0; 				 // Topic: "Nemp - Noch ein Mp3-Player"
  HELP_News = 2; 				 // Topic: "Neuigkeiten"
  HELP_Install = 1; 				 // Topic: "Installation und portable Installation"
  HELP_Wizard = 3; 				 // Topic: "Der Nemp-Wizard"
  HELP_FirstSteps = 4; 				 // Topic: "Erste Schritte"
  HELP_GeneralControl = 5; 				 // Topic: "Allgemeine Bedienung"
  HELP_Portable = 11; 				 // Topic: "Mobile Festplatten, Cloud und Portabilität"
  HELP_PlayerAndPlaylist_Main = 6; 				 // Topic: "Player und Playlist"
  HELP_Controls = 7; 				 // Topic: "Anzeige und Steuerung im Player"
  HELP_EqualizerAndEffects = 14; 				 // Topic: "Equalizer und Effekte"
  HELP_Headphones = 15; 				 // Topic: "Kopfhörer"
  HELP_Playlist = 16; 				 // Topic: "Die Playlist"
  HELP_FavoritePlaylists = 17; 				 // Topic: "Favoriten-Playlists"
  HELP_CleanupPlaylist = 18; 				 // Topic: "Playlist aufräumen"
  HELP_ReplayGain = 19; 				 // Topic: "ReplayGain"
  HELP_SpecialFeatures = 21; 				 // Topic: "Special Features"
  HELP_MediaLibrary_Main = 20; 				 // Topic: "Die Medienbibliothek"
  HELP_BuildMediaLibrary = 22; 				 // Topic: "Medienbibliothek aufbauen und pflegen"
  HELP_BrowseMediaLibrary = 25; 				 // Topic: "Stöbern in der Medienbibliothek"
  HELP_SearchMediaLibrary = 27; 				 // Topic: "Suche in der Medienbibliothek"
  HELP_Categories = 23; 				 // Topic: "Kategorien"
  HELP_Treeview = 24; 				 // Topic: "Ebenen in der Baumansicht"
  HELP_DefinitionAlbum = 26; 				 // Topic: "Definition "Album""
  HELP_CSVExport = 38; 				 // Topic: "CSV-Export"
  HELP_Metadata = 28; 				 // Topic: "Metadaten (ID3-Tags)"
  HELP_Coverart = 34; 				 // Topic: "Coverart"
  HELP_Tools = 29; 				 // Topic: "Tools"
  HELP_TagCloudEditor = 35; 				 // Topic: "Tagwolken-Editor"
  HELP_wdsd = 12; 				 // Topic: "wdsd"
  HELP_WindowModes = 8; 				 // Topic: "Skins, sichtbare Bereiche und Einzelfenster"
  HELP_PartyMode = 9; 				 // Topic: "Party-Modus"
  HELP_Languages = 10; 				 // Topic: "Sprachen"
  HELP_FormDesigner = 13; 				 // Topic: "Form-Designer"
  HELP_Marker = 36; 				 // Topic: "Markierungen"
  HELP_Webradio = 37; 				 // Topic: "Webradio"
  HELP_Settings = 30; 				 // Topic: "Einstellungen"
  HELP_Skins = 31; 				 // Topic: "Skins"
  HELP_NerdStuff = 32; 				 // Topic: "Nerd-Zeug"
  HELP_Versionsgeschichte = 33; 				 // Topic: "Versionsgeschichte"

implementation

end.
