object PlaylistForm: TPlaylistForm
  Left = 218
  Top = 190
  BorderStyle = bsNone
  ClientHeight = 303
  ClientWidth = 420
  Color = clBtnFace
  Constraints.MinHeight = 200
  Constraints.MinWidth = 300
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  KeyPreview = True
  OnClose = FormClose
  OnKeyDown = FormKeyDown
  OnMouseDown = FormMouseDown
  OnMouseMove = FormMouseMove
  OnMouseUp = FormMouseUp
  OnResize = FormResize
  OnShow = FormShow
  TextHeight = 13
  object ContainerPanelPlaylistForm: TNempPanel
    Tag = 1
    Left = 0
    Top = 0
    Width = 420
    Height = 303
    Align = alClient
    BevelOuter = bvNone
    TabOrder = 0
    OnMouseDown = ContainerPanelPlaylistFormMouseDown
    OnMouseMove = ContainerPanelPlaylistFormMouseMove
    OnMouseUp = ContainerPanelPlaylistFormMouseUp
    Ratio = 0
    DrawMode = dm_Windows
    DrawFrame = False
    BackgroundBasePanel = True
    OnPaintBackground = ContainerPanelPlaylistFormPaintBackground
    OwnerDraw = False
    object pnlSplit: TPanel
      AlignWithMargins = True
      Left = 8
      Top = 6
      Width = 404
      Height = 289
      Margins.Left = 8
      Margins.Top = 6
      Margins.Right = 8
      Margins.Bottom = 8
      Align = alClient
      BevelOuter = bvNone
      TabOrder = 0
      ExplicitLeft = 7
      ExplicitTop = 2
      ExplicitWidth = 406
      ExplicitHeight = 294
    end
  end
end
