object ReplayGainProgressForm: TReplayGainProgressForm
  Left = 0
  Top = 0
  Caption = 'Nemp: Calculating ReplayGain'
  ClientHeight = 276
  ClientWidth = 494
  Color = clBtnFace
  Constraints.MinHeight = 280
  Constraints.MinWidth = 510
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OnCloseQuery = FormCloseQuery
  OnCreate = FormCreate
  OnShow = FormShow
  TextHeight = 13
  object pbComplete: TProgressBar
    AlignWithMargins = True
    Left = 8
    Top = 214
    Width = 478
    Height = 17
    Margins.Left = 8
    Margins.Top = 0
    Margins.Right = 8
    Margins.Bottom = 4
    Align = alBottom
    TabOrder = 0
    ExplicitTop = 215
  end
  object LogMemo: TMemo
    AlignWithMargins = True
    Left = 8
    Top = 101
    Width = 478
    Height = 113
    Margins.Left = 8
    Margins.Top = 4
    Margins.Right = 8
    Margins.Bottom = 0
    Align = alClient
    ReadOnly = True
    ScrollBars = ssVertical
    TabOrder = 1
    WordWrap = False
    ExplicitLeft = -2
    ExplicitTop = 100
    ExplicitWidth = 488
    ExplicitHeight = 249
  end
  object pnlButtons: TPanel
    Left = 0
    Top = 235
    Width = 494
    Height = 41
    Align = alBottom
    BevelOuter = bvNone
    TabOrder = 2
    ExplicitTop = 536
    object BtnCancel: TButton
      AlignWithMargins = True
      Left = 395
      Top = 8
      Width = 91
      Height = 25
      Margins.Left = 8
      Margins.Top = 8
      Margins.Right = 8
      Margins.Bottom = 8
      Align = alRight
      Cancel = True
      Caption = 'Cancel'
      TabOrder = 0
      OnClick = BtnCancelClick
    end
    object cbAutoClose: TCheckBox
      AlignWithMargins = True
      Left = 8
      Top = 8
      Width = 371
      Height = 25
      Margins.Left = 8
      Margins.Top = 8
      Margins.Right = 8
      Margins.Bottom = 8
      Align = alClient
      Caption = 'Close window after completion'
      TabOrder = 1
      OnClick = cbAutoCloseClick
    end
  end
  object pnlProgressTitle: TPanel
    AlignWithMargins = True
    Left = 0
    Top = 76
    Width = 494
    Height = 17
    Margins.Left = 0
    Margins.Top = 4
    Margins.Right = 0
    Margins.Bottom = 4
    Align = alTop
    BevelOuter = bvNone
    TabOrder = 3
    ExplicitLeft = 8
    ExplicitTop = 200
    ExplicitWidth = 393
    object LblStatus: TLabel
      AlignWithMargins = True
      Left = 84
      Top = 0
      Width = 402
      Height = 17
      Margins.Left = 8
      Margins.Top = 0
      Margins.Right = 8
      Margins.Bottom = 0
      Align = alClient
      AutoSize = False
      Caption = 'Current item ... reading ....'
      ShowAccelChar = False
      WordWrap = True
      ExplicitTop = -4
      ExplicitWidth = 301
    end
    object pbTrack: TProgressBar
      AlignWithMargins = True
      Left = 8
      Top = 0
      Width = 60
      Height = 17
      Margins.Left = 8
      Margins.Top = 0
      Margins.Right = 8
      Margins.Bottom = 0
      Align = alLeft
      TabOrder = 0
    end
  end
  object pnlHeader: TPanel
    AlignWithMargins = True
    Left = 0
    Top = 8
    Width = 494
    Height = 64
    Margins.Left = 0
    Margins.Top = 8
    Margins.Right = 0
    Margins.Bottom = 0
    Align = alTop
    BevelOuter = bvNone
    TabOrder = 4
    ExplicitTop = 104
    ExplicitWidth = 465
    object MainImage: TVirtualImage
      AlignWithMargins = True
      Left = 8
      Top = 0
      Width = 64
      Height = 64
      Margins.Left = 8
      Margins.Top = 0
      Margins.Right = 8
      Margins.Bottom = 0
      Align = alLeft
      ImageCollection = DataModuleGui.ICGraphics
      ImageWidth = 0
      ImageHeight = 0
      ImageIndex = 39
      ImageName = 'imgReplayGain'
    end
    object LblMain: TLabel
      AlignWithMargins = True
      Left = 80
      Top = 0
      Width = 406
      Height = 64
      Margins.Left = 0
      Margins.Top = 0
      Margins.Right = 8
      Margins.Bottom = 0
      Align = alClient
      AutoSize = False
      Caption = 
        'Nemp is calculating ReplayGain values right now. This may take a' +
        ' while. '#13#10#13#10
      WordWrap = True
      ExplicitLeft = 88
      ExplicitTop = 8
      ExplicitWidth = 398
      ExplicitHeight = 56
    end
  end
  object CloseTimer: TTimer
    Enabled = False
    OnTimer = CloseTimerTimer
    Left = 32
    Top = 112
  end
end
